---
 - name: 
   yum:
    name: 
     - mariadb
     - mariadb-server
     - php
    state: present

 - name: secure mariadb
   command: 'echo "& y y Mypasswd Mypasswd y y y y" | ./usr/bin/mysql_secure_installation'

 - name: copier les fichier de l'app
   copy: 
    src: files/
    dest: /var/www/html


